### ISSUE TITLE
SwipetoRefreshLayout

### ISSUE THREAD

**Issue by efratos1** [dbsheta/android-paging-network-and-database#1]
it is a grate project you got there it helped me a lot  but i was wondering how to implement SwipetoRefreshLayout. thank you

**Comment by dbsheta** [comment]
Hi @efratos1. Sorry I wasn't able to get back to you on this, got involved in non-android projects at work. It seems you have figured a way out. It would be great if you can share your code/gist for SwipetoRefreshLayout functionality

**Comment by efratos1** [comment]
It is simple first you have to get the the position [0] item from db order by DESC from db then get the id then send that id to your server fetch all using the id as offset then on data fetched successfully add it to your db the Livedata will Handel the rest
